### ISSUE TITLE
user wants list of titles by city (alphabetical)

### ISSUE THREAD

**Issue by srabun** [uoregon-libraries/oregonnews#33]
all current title lists are alphabetical by title, which makes it difficult to find multiple titles from the same city. Would be nice to create a page that lists titles by city, with cities in alphabetical order, to improve research ability and make it easier to find multiple titles from the same city.

**Comment by srabun** [comment]
Maybe instead of creating a new page, we could add the "toggle" functionality to this page: http://oregonnews.uoregon.edu/newspapers/ in the "Newspapers" column add a button to list alphabetically by city as opposed to the default of alphabetical by title?

**Comment by jechols** [comment]
Added a ticket for the sort toggle - it's a good idea either way.

However, it's worth noting that we already have this functionality.  I'm not sure when it got added, but clicking a city from the home page now brings you to a list of papers in that city.  It's probably worth fixing up the search form, too, but that may be an open-oni thing rather than here.
